### ISSUE TITLE
Docs not found in Windows build

### ISSUE THREAD

**Issue by sixy6e** [ausseabed/qax#29]
On Windows builds, the html docs are not found and fails when attempting to open them:

```python
File "hyo2\qax\app\mainwin.py", line 279, in open_manual
    ManualWindow.show_manual()
  File "hyo2\qax\app\widgets\qax\manual.py", line 28, in show_manual
    man_win = ManualWindow()
              ^^^^^^^^^^^^^^
  File "hyo2\qax\app\widgets\qax\manual.py", line 81, in __init__
    self.initialUrl = QUrl(self.docs_url())
                           ^^^^^^^^^^^^^^^
  File "hyo2\qax\app\widgets\qax\manual.py", line 100, in docs_url
    raise RuntimeError("Docs not found at {}".format(abs_docs_oath))
```

**Comment by lachlanhurst** [comment]
If this is in a dev environment I believe you need to build the docs separately.

    cd docs
    make html

Restart QAX and docs should work

**Comment by sixy6e** [comment]
Unfortunately not the case. In updating pyinstaller due to setuptools updates (both were falling very far behind), the pyinstaller build now creates an _internal directory to dump everything into, as opposed to some pieces inside and some pieces outside the qax build.

Anyway, the latest commits have resolved this.
