### ISSUE TITLE
Unhandled exception upon startup with QtAwesome icons

### ISSUE THREAD

**Issue by mattwilson27** [ausseabed/qax#9]
Greetings! Experienced crash upon startup when attempting to run QAX on NOAA-configured PC. I attached the unhandled exception. Regards, Matt
![image](https://user-images.githubusercontent.com/78967275/133296140-5482d350-2d46-4902-aa61-9d010354cb76.png)

**Comment by giumas** [comment]
@lachlanhurst I am able to replicate the same issue also running QAX on Pydro. 

It may be related to [KB-3053676](https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/feature-to-block-untrusted-fonts ), but no way to check it given the local user restrictions.

For another project, a similar issue was resolved by downgrading QtAwesome to a version that does not load fonts.

**Comment by lachlanhurst** [comment]
Thanks for looking into this @giumas . 

It's a rather unfortunate issue; the idea of including QTAwesome was to make it easier to include common icons without needing to include a raster file for each one. But based on what you've found it seems the only workaround is to do just that.

Your PR (#10) looks good thanks again! Will likely merge soon, just need some time to modify the registry to reproduce the issue and confirm the fix from here.

I'm considering modifying your `qta.py` utility class to generate the raster versions of the icons (using the QTawesome fonts) if they are requested and do not exist. This would only happen if the application was run in a developer mode. Idea being it would save developers from having to create raster versions of the icons, developers would still be responsible for committing these automatically generated files. That's outside the scope of this issue/PR.
